import { useState, useRef } from 'react';
import { Card, CardMedia, CardContent, Zoom, Modal, Box, Typography } from '@mui/material';

const DallEPictureCard = () => {
    const [open, setOpen] = useState(false);
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);

    const style = {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: 400,
        bgcolor: 'background.paper',
        boxShadow: 24,
        p: 4,
      };

    return (
        <Box >
            <Card sx={{m:3}} onClick={handleOpen}>
                <CardMedia
                    sx={{width:'100%', height:500}}
                    image={'/static/dalleGenerated/stackOfCash.png'}
                    title="guy thinking"
                    />
            </Card>
            <Modal
                open={open}
                onClose={handleClose}
            >
                <Box sx={style}>
                    <Typography variant='h6'>This image was generated by Dall-E.</Typography>
                    <Typography variane='body1'>
                        Prompt: "minimalist digital art of a man pondering over a stack of cash, with dark blue and orange color scheme"
                    </Typography>
                </Box>
            </Modal>
        </Box>
    )
}

export default DallEPictureCard;