import { useState, useRef } from 'react';
import { Card, CardMedia, Link, Modal, Box, Typography } from '@mui/material';

const DallEPictureCard = ({prompt}) => {
    const [open, setOpen] = useState(false);
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);

    const style = {
        position: 'absolute',
        top: '75%',
        left: '82.5%',
        transform: 'translate(-50%, -50%)',
        width: 400,
        bgcolor: 'background.paper',
        boxShadow: 24,
        p: 4,
      };

    return (
        <Box >
            <Card sx={{m:3}} onClick={handleOpen}>
                <CardMedia
                    sx={{width:'100%', height:500}}
                    image={'/static/dalleGenerated/stackOfCash.png'}
                    title="guy thinking"
                    />
            </Card>
            <Modal
                open={open}
                onClose={handleClose}
            >
                <Box sx={style}>
                    <Typography variant='h6'>This image was generated by <Link href="https://openai.com/product/dall-e-2">Dall-E</Link></Typography>
                    <Typography variane='body1'>
                        Prompt: {prompt}
                    </Typography>
                </Box>
            </Modal>
        </Box>
    )
}

export default DallEPictureCard;